[package]
name = "stage1"
version = "0.1.0"
authors = ["Didier Plaindoux <d.plaindoux@free.fr>"]
edition = "2018"

[dependencies]
bencher = "0.1"
response ={ version = "0.1.0", path = "../response" }

[profile.release]
lto = "fat"
codegen-units = 1

[[bench]]
name = "parser"
harness = false
